apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cigna-keyvault-secrets
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "cigna-dev-kv-001"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: app-message
          objectType: secret
          objectVersion: ""
    tenantId: "37a69e19-59af-41c1-ac91-36b102aab8ce"
